//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modells
{
    using System;
    using System.Collections.Generic;
    
    public partial class admin
    {
        public int adminId { get; set; }
        public string adminLogin { get; set; }
        public string adminPassword { get; set; }
        public string adminEmail { get; set; }
        public string adminPictureUrl { get; set; }
    }
}
