//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Modells
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class picture
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public picture()
        {
            this.comments = new HashSet<comments>();
        }
    
        public int pictureId { get; set; }
        [Display (Name ="Titre")]
        public string pictureTitle { get; set; }
        [Display(Name = "Titre alternatif")]
        public string pictureAlternateTitle { get; set; }
        [Display(Name = "Description")]
        public string pictureDescription { get; set; }
        [Display(Name = "Image")]
        public string pictureStandardUrl { get; set; }
        [Display(Name = "Rating")]
        public Nullable<short> pictureRatingValue { get; set; }
        [Display(Name = "Vues")]
        public Nullable<short> pictureViewsNumber { get; set; }
        public int categoryId { get; set; }
    
        public virtual category category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<comments> comments { get; set; }
    }
}
